---
- name: install nrpe
  hosts: local
  become: true
  tasks:  

  - name: install epel-repository
    yum:
      name: 
      - epel-release
      - nrpe
      - nagios-plugins-all
      state: present
 

  - name: Add nagios server details
    replace:
      path: /etc/nagios/nrpe.cfg
      regexp: '^#(.*allowed_hosts=127.0.0.1.*)'
      replace: 'allowed_hosts=127.0.0.1, 172.31.44.31'


  - name: Start and Enable nrpe service
    service: name=nrpe state=started enabled=yes
